//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook_Messenger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Facebook_Messenger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Attach {
            get {
                object obj = ResourceManager.GetObject("Attach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* GENERAL */
        ///
        ///body {
        /// overflow: hidden;
        /// text-rendering: optimizeLegibility;
        /// -webkit-font-smoothing: antialiased;
        ///}
        ///
        ///#pagelet_bluebar, #pagelet_dock, #rightCol, #pagelet_sidebar, #leftCol {
        /// display: none !Important;
        ///}
        ///
        ///.uiScrollableAreaBody, ._2nb, ._2nc, ._5uj5, ._4rw, .fbx, .noFooter, ._5p3y, _li, body, #content, .fb_content, #contentArea, #contentCol, #mainContainer, ._li, #globalContainer, .uiContextualLayerParent, #contentCol, #pagelet_web_messenger, .fbx #globalContainer {
        /// width: 100v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSS {
            get {
                return ResourceManager.GetString("CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DisabledButtons {
            get {
                object obj = ResourceManager.GetObject("DisabledButtons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Emoticon {
            get {
                object obj = ResourceManager.GetObject("Emoticon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image {
            get {
                object obj = ResourceManager.GetObject("Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Inner {
            get {
                object obj = ResourceManager.GetObject("Inner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Messenger {
            get {
                object obj = ResourceManager.GetObject("Messenger", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Outer {
            get {
                object obj = ResourceManager.GetObject("Outer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window.dockBadge = &apos;&apos;;
        ///setTimeout(updateBadge, 1000);
        ///setTimeout(updateBadge, 3000);
        ///setInterval(updateBadge, 5000);
        ///
        ///function updateBadge() {
        ///	var newBadge = &apos;&apos;;
        ///	var regex = /\s*\((\d+)\)\s*/;
        ///	var text = document.title;
        ///	
        ///	if (text.length) {
        ///		//console.log(&apos;text: &apos; + text);
        ///		var res = text.match(regex);
        ///		//console.log(&apos;res: &apos; + res);
        ///		if (res &amp;&amp; res.length &gt; 1) {
        ///			newBadge = res[1];
        ///			//console.log(&apos;newBadge: &apos; + newBadge);
        ///		}
        ///	}
        ///	
        ///	window.dockBadge = newBadge;
        ///}.
        /// </summary>
        internal static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
    }
}
